### PR TITLE
Fix UTXO index

### LINKED ISSUE #1543: Data loss in UTXO index
There are two scenarios in which data loss in the UTXO index could occur:

* If kaspad crashes/closes after inserting a block but before it was added to the UTXO index, the index would never learn of this UTXO. Meaning that it's possible to lose UTXOs between kaspad runs.
* If kaspad enters IBD and is required to download the pruning point's UTXO set, the UTXO index is never updated. This essentially corrupts the index.

### PR DESCRIPTION
**Pull request by someone235**
Fixes #1543

### CODE REVIEW

File: domain/consensus/processes/blockprocessor/validateandinsertblock.go [hunk 1]
```diff
@@ -145,8 +146,15 @@ func (bp *blockProcessor) validateAndInsertBlock(block *externalapi.DomainBlock,
 
 	bp.blockLogger.LogBlock(block)
 
+	virtualParents, err := bp.dagTopologyManager.Parents(model.VirtualBlockHash)
+	if err != nil {
+		return nil, err
+	}
+
```
Comment (elichai) [inline domain/consensus/processes/blockprocessor/validateandinsertblock.go:153]: I think we want `LogBlock` to be the last logic thing in ValidateAndInsertBlock

File: infrastructure/network/netadapter/server/grpcserver/protowire/rpc.proto [hunk 2]
```diff
@@ -546,6 +546,40 @@ message VirtualSelectedParentBlueScoreChangedNotificationMessage {
...
+// StopNotifyPruningPointUTXOSetOverrideRequestMessage unregisters this connection for
+// pruning point UTXO set override notifications.
+//
+// This call is only available when this kaspad was started with `--utxoindex`
+//
+// See: PruningPointUTXOSetOverrideNotificationMessage
+message StopNotifyPruningPointUTXOSetOverrideRequestMessage {
+}
+
+message StopNotifyPruningPointUTXOSetOverrideResponseMessage {
```
Comment (elichai) [inline infrastructure/network/netadapter/server/grpcserver/protowire/rpc.proto:579]: In previous places we've called it `StopNotifying`

File: infrastructure/network/rpcclient/rpc_on_pruning_point_utxo_set_override.go [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+	if err != nil {
+		return err
+	}
+	notifyPruningPointUTXOSetOverrideResponse := response.(*appmessage.NotifyPruningPointUTXOSetOverrideResponseMessage)
+	if notifyPruningPointUTXOSetOverrideResponse.Error != nil {
+		return c.convertRPCError(notifyPruningPointUTXOSetOverrideResponse.Error)
+	}
+	spawn("RegisterPruningPointUTXOSetNotifications", func() {
+		for {
+			_, err := c.route(appmessage.CmdPruningPointUTXOSetOverrideNotificationMessage).Dequeue()
```
Comment (elichai) [inline infrastructure/network/rpcclient/rpc_on_pruning_point_utxo_set_override.go:27]: Should we downcast the message to `PruningPointUTXOSetOverrideNotificationMessage` as a sanity check?

File: infrastructure/network/rpcclient/rpc_on_pruning_point_utxo_set_override.go [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+	response, err := c.route(appmessage.CmdStopNotifyPruningPointUTXOSetOverrideResponseMessage).DequeueWithTimeout(c.timeout)
+	if err != nil {
+		return err
+	}
+	stopNotifyPruningPointUTXOSetOverrideResponse := response.(*appmessage.StopNotifyPruningPointUTXOSetOverrideResponseMessage)
+	if stopNotifyPruningPointUTXOSetOverrideResponse.Error != nil {
+		return c.convertRPCError(stopNotifyPruningPointUTXOSetOverrideResponse.Error)
+	}
+	return nil
+}
```
Comment (elichai) [inline infrastructure/network/rpcclient/rpc_on_pruning_point_utxo_set_override.go:57]: Thanks! I see that in the other notifications we don't provide this nice helper

File: testing/integration/utxo_index_test.go [hunk 5]
```diff
@@ -70,21 +70,11 @@ func TestUTXOIndex(t *testing.T) {
...
-	mineNextBlock(t, kaspad)
-	notification := <-onUTXOsChangedChan
-	if len(notification.Removed) > 0 {
-		t.Fatalf("Unexpectedly received that a UTXO has been removed")
-	}
-	for _, added := range notification.Added {
-		notificationEntries = append(notificationEntries, added)
-	}
-
-	// Mine another block to accept the above block
```
Comment (elichai) [inline testing/integration/utxo_index_test.go:83]: Why did you remove this?

File: infrastructure/network/netadapter/server/grpcserver/protowire/messages_grpc.pb.go [hunk 6]
```diff
@@ -11,7 +11,7 @@ import (
 
 // This is a compile-time assertion to ensure that this generated file
 // is compatible with the grpc package it is being compiled against.
-const _ = grpc.SupportPackageIsVersion7
+const _ = grpc.SupportPackageIsVersion6
```
Comment (elichai) [inline infrastructure/network/netadapter/server/grpcserver/protowire/messages_grpc.pb.go:14]: Why did this change?

File: domain/utxoindex/utxoindex.go [hunk 7]
```diff
@@ -20,143 +17,143 @@ type UTXOIndex struct {
 }
 
 // New creates a new UTXO index
-func New(consensus externalapi.Consensus, database database.Database) *UTXOIndex {
-	store := newUTXOIndexStore(database)
-	return &UTXOIndex{
+func New(consensus externalapi.Consensus, database database.Database) (*UTXOIndex, error) {
```
Comment (elichai) [inline domain/utxoindex/utxoindex.go:20]: We should document that this should run *before* the flows. otherwise the virtual can be changed between `isSynced()` and registering

File: domain/utxoindex/utxoindex.go [hunk 8]
```diff
@@ -20,143 +17,143 @@ type UTXOIndex struct {
...
+		return err
+	}
+
+	var fromOutpoint *externalapi.DomainOutpoint
+	for {
+		const step = 1000
+		virtualUTXOs, err := ui.consensus.GetVirtualUTXOs(virtualInfo.ParentHashes, fromOutpoint, step)
 		if err != nil {
-			return nil, err
+			return err
```
Comment (elichai) [inline domain/utxoindex/utxoindex.go:58]: Do we want to check the error and restart the loop if the parents changed? or do we assert here that the flows are off and if they're not then we want to crash here?

File: domain/utxoindex/serialization.go [hunk 9]
```diff
@@ -0,0 +1,74 @@
+package utxoindex
```
Comment (elichai) [inline domain/utxoindex/serialization.go:1]: nit, I prefer that these functions will be free(no receiver)

File: testing/integration/utxo_index_test.go (hunk 5 above)
Comment (someone235) [reply testing/integration/utxo_index_test.go:83]: Because the notification are now based on the virtual and not on the selected tip, so you don't need to mine extra block to get the expected notification

File: domain/utxoindex/utxoindex.go (hunk 8 above)
Comment (someone235) [reply domain/utxoindex/utxoindex.go:58]: Yeah, I think I prefer to assert

**Review by elichai — APPROVED** [review]
