### PR TITLE
Fix two pruning proof bugs

### LINKED ISSUE #1886: IBD panics with flow-HandleRelayInvs error (kaspad 0.11.8 stability)
It appears kaspad 0.11.8 is crashing upon initiation of IBD with the following error:
```
2021-12-15 00:44:59.272 [CRT] PROT: Exiting: Fatal error in goroutine `flow-HandleRelayInvs 41`: not found
key 012f092f626c6f636b2d72656c6174696f6e732ffdd28ba9de48d83a7a0748b42e80d78bfb8b7cae569b6575cef72e5f89628815 not found
```

Please find complete logs below:
```
2021-12-15 00:39:43.064 [INF] KASD: Version 0.11.8
2021-12-15 00:39:43.064 [INF] KASD: Loading database from 'C:\Users\aspect\.kdx\data\kaspad-kd0\kaspa-mainnet\datadir2'
2021-12-15 00:39:43.064 [INF] KASD: Profile server listening on :7000
2021-12-15 00:39:43.929 [INF] ADXR: Loaded 4096 addresses and 0 banned addresses
2021-12-15 00:39:44.034 [INF] KASD: UTXO index started
2021-12-15 00:39:44.034 [INF] TXMP: P2P Server listening on [::]:16111
2021-12-15 00:39:44.034 [INF] TXMP: RPC Server listening on [::]:16110
2021-12-15 00:39:44.035 [INF] CMGR: Connecting to 192.169.108.36:16111
2021-12-15 00:39:45.057 [INF] CMGR: Connecting to 104.207.128.241:16111
2021-12-15 00:39:45.830 [INF] TXMP: RPC Incoming connection from 127.0.0.1:63969
2021-12-15 00:39:46.065 [INF] CMGR: Connecting to 192.169.104.96:16111
2021-12-15 00:39:47.078 [INF] CMGR: Connecting to [2a00:a040:197:693:5cf0:1a18:4b8d:de6e]:16111
2021-12-15 00:39:48.091 [INF] CMGR: Connecting to 135.181.180.91:16111
2021-12-15 00:39:48.338 [INF] TXMP: P2P Connected to 135.181.180.91:16111
2021-12-15 00:39:48.338 [INF] CMGR: Connecting to [2a00:23c5:a605:5600:849c:2937:356b:b2ee]:16111
2021-12-15 00:39:49.348 [INF] CMGR: Connecting to 18.133.247.173:16111
2021-12-15 00:39:50.361 [INF] CMGR: Connecting to 65.108.0.211:16111
2021-12-15 00:40:14.047 [INF] CMGR: Connecting to [2409:8a74:6288:5ef0:b918:51c8:1734:8708]:16111
2021-12-15 00:40:15.053 [INF] CMGR: Connecting to 192.169.101.60:16111
2021-12-15 00:40:16.061 [INF] CMGR: Connecting to [240e:474:ff5e:5e05:3547:7617:189a:82a6]:16111
2021-12-15 00:40:17.066 [INF] CMGR: Connecting to 192.169.1.254:16111
2021-12-15 00:40:18.073 [INF] CMGR: Connecting to [2a01:e0a:847:d1d0:c9ea:85a3:7b9e:f7d3]:16111
2021-12-15 00:40:19.074 [INF] CMGR: Connecting to [2a00:a040:19a:1d2:a8ac:bf82:5275:b890]:16111
2021-12-15 00:40:20.088 [INF] CMGR: Connecting to [2408:8220:6d19:f5a0:e843:d02f:292e:99cf]:16111
2021-12-15 00:40:44.046 [INF] CMGR: Connecting to 192.169.102.50:16111
2021-12-15 00:40:45.049 [INF] CMGR: Connecting to [2001:4df4:508:8000:49cd:f11a:9cea:e394]:16111
2021-12-15 00:40:46.057 [INF] CMGR: Connecting to 192.169.107.95:16111
2021-12-15 00:40:47.059 [INF] CMGR: Connecting to [2a01:110:68:40::141c]:16111
2021-12-15 00:40:48.065 [INF] CMGR: Connecting to [2409:8a1a:162:dba0:4509:9b41:7ca9:a19d]:16111
2021-12-15 00:40:49.070 [INF] CMGR: Connecting to 18.133.195.140:16111
2021-12-15 00:40:50.071 [INF] CMGR: Connecting to 192.169.103.8:16111
2021-12-15 00:41:14.050 [INF] CMGR: Connecting to 192.169.101.84:16111
2021-12-15 00:41:15.056 [INF] CMGR: Connecting to 192.169.104.2:16111
2021-12-15 00:41:16.061 [INF] CMGR: Connecting to 60.205.157.90:16111
2021-12-15 00:41:17.066 [INF] CMGR: Connecting to [240e:330:3eb2:e00:493c:2d56:8ad5:279f]:16111
2021-12-15 00:41:18.069 [INF] CMGR: Connecting to 192.169.109.30:16111
2021-12-15 00:41:19.083 [INF] CMGR: Connecting to 192.169.108.70:16111
2021-12-15 00:41:20.088 [INF] CMGR: Connecting to [2408:821a:8b21:bdb0:7cfb:aa09:428f:d7b7]:16111
2021-12-15 00:41:44.037 [INF] CMGR: Connecting to 40.0.0.1:16111
2021-12-15 00:41:45.042 [INF] CMGR: Connecting to [2409:8a34:1a37:feb0:91dd:4a51:15f5:874d]:16111
2021-12-15 00:41:46.054 [INF] CMGR: Connecting to [2a02:ed0:6f3b:5d00:2379:547a:3b6d:7447]:16111
2021-12-15 00:41:47.061 [INF] CMGR: Connecting to [2408:8220:6d17:4410:2893:ecb7:e1c7:3db0]:16111
2021-12-15 00:41:48.074 [INF] CMGR: Connecting to [2409:8a30:c493:5190:a150:1dd0:c7d4:6335]:16111
2021-12-15 00:41:49.087 [INF] CMGR: Connecting to [2a02:1205:34e5:d230:f1ab:40ad:8a98:7d13]:16111
2021-12-15 00:41:50.094 [INF] CMGR: Connecting to [2a01:4f9:3b:2459::2]:16111
2021-12-15 00:42:14.039 [INF] CMGR: Connecting to [2001:0:348b:fb58:c5d:af60:730f:9ce7]:16111
2021-12-15 00:42:15.053 [INF] CMGR: Connecting to 18.133.155.172:16111
2021-12-15 00:42:16.057 [INF] CMGR: Connecting to 192.169.107.58:16111
2021-12-15 00:42:17.060 [INF] CMGR: Connecting to [240e:3b3:d04f:f010:fc45:cb37:5e14:b01d]:16111
2021-12-15 00:42:18.075 [INF] CMGR: Connecting to 192.169.108.143:16111
2021-12-15 00:42:19.078 [INF] CMGR: Connecting to 192.169.108.73:16111
2021-12-15 00:42:20.088 [INF] CMGR: Connecting to [2a01:4f8:221:1a53::2]:16111
2021-12-15 00:42:44.051 [INF] CMGR: Connecting to 192.169.103.70:16111
2021-12-15 00:42:45.053 [INF] CMGR: Connecting to [2a00:a040:19f:b973:6566:a029:a934:9f5c]:16111
2021-12-15 00:42:46.062 [INF] CMGR: Connecting to [64:ff9b::3625:708]:16111
2021-12-15 00:42:47.075 [INF] CMGR: Connecting to [2a01:4f9:6a:4f2f::2]:16111
2021-12-15 00:42:48.076 [INF] CMGR: Connecting to [2a00:a040:1a1:6819:40a4:bb56:9fe5:9e4f]:16111
2021-12-15 00:42:49.082 [INF] CMGR: Connecting to 192.169.107.10:16111
2021-12-15 00:42:50.084 [INF] CMGR: Connecting to 3.8.187.115:16111
2021-12-15 00:43:14.038 [INF] CMGR: Connecting to [2603:8081:1401:9415:9588:967f:c097:8d11]:16111
2021-12-15 00:43:15.053 [INF] CMGR: Connecting to [2408:8215:6728:4a40:f99b:233d:ef5c:7d96]:16111
2021-12-15 00:43:16.067 [INF] CMGR: Connecting to [2a01:4f9:6b:5068::2]:16111
2021-12-15 00:43:17.075 [INF] CMGR: Connecting to [2409:8a44:534:f790:2850:6ac0:f963:908f]:16111
2021-12-15 00:43:18.079 [INF] CMGR: Connecting to [2a00:a040:19a:1d2:3d41:c2d7:dd32:79d1]:16111
2021-12-15 00:43:19.086 [INF] CMGR: Connecting to [2a02:908:fbd2:26e0:6822:4943:ca7c:f1d2]:16111
2021-12-15 00:43:20.092 [INF] CMGR: Connecting to [2408:821b:8b20:cca0:18dd:e524:c59e:fbe9]:16111
2021-12-15 00:43:44.040 [INF] CMGR: Connecting to [2409:8a1a:162:dba0:c941:619d:d6c1:a644]:16111
2021-12-15 00:43:45.044 [INF] CMGR: Connecting to 192.169.104.69:16111
2021-12-15 00:43:46.057 [INF] CMGR: Connecting to [2605:a601:ac92:7900:654e:d09a:2a4f:a51a]:16111
2021-12-15 00:43:47.058 [INF] CMGR: Connecting to [240e:3b7:3278:b210:b84a:1e10:4dbd:461b]:16111
2021-12-15 00:43:48.066 [INF] CMGR: Connecting to [240e:3b2:6203:e9b0:b5c9:c009:3830:4691]:16111
2021-12-15 00:43:49.077 [INF] CMGR: Connecting to 192.169.104.79:16111
2021-12-15 00:43:50.080 [INF] CMGR: Connecting to [2409:8a44:513:84c0:c176:bb8f:c182:cd54]:16111
2021-12-15 00:44:14.039 [INF] CMGR: Connecting to 192.169.105.80:16111
2021-12-15 00:44:15.044 [INF] CMGR: Connecting to [2409:8a1a:16f:de60:15f:17c1:8ba6:ef2c]:16111
2021-12-15 00:44:16.047 [INF] CMGR: Connecting to [2a00:a040:189:d2f9:4833:1c35:5a19:53fc]:16111
2021-12-15 00:44:17.057 [INF] CMGR: Connecting to [2a02:6680:2130:34ec:78f7:2a6b:aaf0:11b2]:16111
2021-12-15 00:44:18.061 [INF] CMGR: Connecting to 192.169.105.56:16111
2021-12-15 00:44:19.068 [INF] CMGR: Connecting to [240e:3a1:86e:f620:c082:ab9c:f2fa:86dd]:16111
2021-12-15 00:44:20.074 [INF] CMGR: Connecting to [2003:dc:df12:bc87:9124:a5f3:c79f:d358]:16111
2021-12-15 00:44:44.036 [INF] CMGR: Connecting to [2409:8920:b201:97c:ac6b:357f:aba2:5b4c]:16111
2021-12-15 00:44:45.041 [INF] CMGR: Connecting to 84.215.4.105:16111
2021-12-15 00:44:45.271 [INF] TXMP: P2P Connected to 84.215.4.105:16111
2021-12-15 00:44:45.271 [INF] CMGR: Connecting to [2408:821b:8b20:cca0:e595:c500:30c5:66ab]:16111
2021-12-15 00:44:45.879 [INF] PROT: IBD started
2021-12-15 00:44:46.006 [INF] PROT: Starting IBD with headers proof
2021-12-15 00:44:46.024 [INF] PROT: Downloading the pruning point proof from <44949da117d2cb75ee839e6ab94d5379: 84.215.4.105:16111>
2021-12-15 00:44:46.277 [INF] CMGR: Connecting to [2409:8a1a:168:b900:90c1:3a8a:caf9:c5e5]:16111
2021-12-15 00:44:47.285 [INF] CMGR: Connecting to 192.169.108.46:16111
2021-12-15 00:44:48.298 [INF] CMGR: Connecting to 192.169.103.74:16111
2021-12-15 00:44:49.302 [INF] CMGR: Connecting to [2001:0:348b:fb58:14e2:106f:d47a:338e]:16111
2021-12-15 00:44:59.272 [INF] PROT: IBD finished (interrupted)
2021-12-15 00:44:59.272 [CRT] PROT: Exiting: Fatal error in goroutine `flow-HandleRelayInvs 41`: not found
key 012f092f626c6f636b2d72656c6174696f6e732ffdd28ba9de48d83a7a0748b42e80d78bfb8b7cae569b6575cef72e5f89628815 not found
github.com/kaspanet/kaspad/infrastructure/db/database/ldb.(*LevelDB).Get
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/infrastructure/db/database/ldb/leveldb.go:69
github.com/kaspanet/kaspad/domain/consensus/database.(*dbManager).Get
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/database/dbmanager.go:13
github.com/kaspanet/kaspad/domain/consensus/datastructures/blockrelationstore.(*blockRelationStore).BlockRelation
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/datastructures/blockrelationstore/block_relation_store.go:51
github.com/kaspanet/kaspad/domain/consensus/processes/dagtopologymanager.(*dagTopologyManager).Parents
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/dagtopologymanager/dagtopologymanager.go:35
github.com/kaspanet/kaspad/domain/consensus/processes/pruningproofmanager.(*pruningProofManager).ValidatePruningPointProof
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/pruningproofmanager/pruningproofmanager.go:496
github.com/kaspanet/kaspad/domain/consensus.(*consensus).ValidatePruningPointProof
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/consensus.go:743
github.com/kaspanet/kaspad/app/protocol/flows/blockrelay.(*handleRelayInvsFlow).syncAndValidatePruningPointProof
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/blockrelay/ibd_with_headers_proof.go:95
github.com/kaspanet/kaspad/app/protocol/flows/blockrelay.(*handleRelayInvsFlow).downloadHeadersAndPruningUTXOSet
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/blockrelay/ibd_with_headers_proof.go:112
github.com/kaspanet/kaspad/app/protocol/flows/blockrelay.(*handleRelayInvsFlow).ibdWithHeadersProof
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/blockrelay/ibd_with_headers_proof.go:20
github.com/kaspanet/kaspad/app/protocol/flows/blockrelay.(*handleRelayInvsFlow).runIBDIfNotRunning
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/blockrelay/ibd.go:53
github.com/kaspanet/kaspad/app/protocol/flows/blockrelay.(*handleRelayInvsFlow).processOrphan
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/blockrelay/handle_relay_invs.go:308
github.com/kaspanet/kaspad/app/protocol/flows/blockrelay.(*handleRelayInvsFlow).start
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/blockrelay/handle_relay_invs.go:147
github.com/kaspanet/kaspad/app/protocol/flows/blockrelay.HandleRelayInvs
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/blockrelay/handle_relay_invs.go:59
github.com/kaspanet/kaspad/app/protocol.(*Manager).registerBlockRelayFlows.func2
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/protocol.go:179
github.com/kaspanet/kaspad/app/protocol.(*Manager).registerFlowForRoute.func1
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/protocol.go:321
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows.func1
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/manager.go:79
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:83
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:32
runtime.goexit
        C:/Program Files/Go/src/runtime/asm_amd64.s:1581
2021-12-15 00:44:59.272 [CRT] PROT: Goroutine stack trace: goroutine 468 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1({0xc026a9c4e0, 0x14}, 0xc000125340)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:30 +0x35
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows(0xc771b8, {0xc007eb0240, 0x11, 0xc006604cf0}, 0xc0001c2140, 0xc006604960, 0xc006616f50)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/manager.go:78 +0x65
github.com/kaspanet/kaspad/app/protocol.(*Manager).routerInitializer.func1()
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/protocol.go:90 +0x575
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc0001d5c80, {0xc028d83000, 0xad2, 0x1000}, {0xb7fe07, 0xc01cdac640}, 0xc01d8f9bc0)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:83 +0x297
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1()
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:32 +0x35
created by github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:31 +0xfd

2021-12-15 00:44:59.272 [CRT] PROT: Stack trace: goroutine 473 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
github.com/kaspanet/kaspad/util/panics.HandlePanic(0x2, {0xc0240eaa20, 0x17}, {0xc0140e8800, 0x4fd, 0x800})
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:22 +0xfd
panic({0xad5700, 0xc0523f0ca8})
        C:/Program Files/Go/src/runtime/panic.go:1038 +0x215
github.com/kaspanet/kaspad/app/protocol/flowcontext.(*FlowContext).HandleError(0xc006604a50, {0xc5e3e0, 0xc0523f0ca8}, {0xb75933, 0xf}, 0xc006616ed0, 0x1c081010eb8)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flowcontext/errors.go:22 +0x1b3
github.com/kaspanet/kaspad/app/protocol.(*Manager).registerFlowForRoute.func1(0x10)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/protocol.go:323 +0x88
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows.func1()
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/manager.go:79 +0x2a
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc0001d5c80, {0xc0140e8800, 0x4fd, 0x800}, {0xc026a9c4e0, 0x8c6966}, 0xc000125340)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:83 +0x297
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1()
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:32 +0x35
created by github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:31 +0xfd

2021-12-15 00:45:02.776 [INF] KASD: Version 0.11.8
2021-12-15 00:45:02.777 [INF] KASD: Loading database from 'C:\Users\aspect\.kdx\data\kaspad-kd0\kaspa-mainnet\datadir2'
2021-12-15 00:45:02.777 [INF] KASD: Profile server listening on :7000
2021-12-15 00:45:02.831 [INF] PRFX: Deleting database prefix &{0}
2021-12-15 00:45:03.644 [INF] ADXR: Loaded 4096 addresses and 0 banned addresses
2021-12-15 00:45:03.745 [INF] KASD: UTXO index started
2021-12-15 00:45:03.745 [INF] TXMP: P2P Server listening on [::]:16111
2021-12-15 00:45:03.745 [INF] TXMP: RPC Server listening on [::]:16110
2021-12-15 00:45:03.746 [INF] CMGR: Connecting to [2408:821a:8b20:ef40:f42c:cdfc:2fa1:8a5e]:16111
2021-12-15 00:45:04.762 [INF] CMGR: Connecting to 192.169.103.12:16111
2021-12-15 00:45:05.776 [INF] CMGR: Connecting to [2a00:a040:19b:4731:85e9:cd8e:df5b:f987]:16111
2021-12-15 00:45:06.454 [INF] TXMP: RPC Incoming connection from 127.0.0.1:55640
2021-12-15 00:45:06.776 [INF] CMGR: Connecting to [2a10:8010:73fa:0:44c7:7e7b:18e5:33a4]:16111
2021-12-15 00:45:07.779 [INF] CMGR: Connecting to 192.169.105.55:16111
2021-12-15 00:45:08.785 [INF] CMGR: Connecting to [2001:0:348b:fb58:2c59:38f3:84c8:1155]:16111
2021-12-15 00:45:09.797 [INF] CMGR: Connecting to [2408:8471:c902:5f:8550:df15:79e6:56d4]:16111
2021-12-15 00:45:10.810 [INF] CMGR: Connecting to 192.169.109.62:16111
2021-12-15 00:45:11.815 [INF] CMGR: No ongoing connections, trying to get new addresses from seed...
2021-12-15 00:45:11.900 [INF] CMGR: DNS discovery failed on seed n.kaspa.turkel.in: lookup n.kaspa.turkel.in: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2021-12-15 00:45:11.909 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-1.kaspanet.org
2021-12-15 00:45:11.959 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-2.kaspanet.org
2021-12-15 00:45:11.978 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed.daglabs-dev.com
2021-12-15 00:45:33.749 [INF] CMGR: Connecting to [240e:3b7:3275:c930:50db:f58a:5400:a544]:16111
2021-12-15 00:45:34.763 [INF] CMGR: Connecting to 192.169.106.49:16111
2021-12-15 00:45:35.773 [INF] CMGR: Connecting to [2a01:e0a:8d2:56f0:d8a8:a34a:5ba6:442d]:16111
2021-12-15 00:45:36.786 [INF] CMGR: Connecting to [2408:8215:6728:4a40:20d3:eac2:415f:a7d2]:16111
2021-12-15 00:45:37.797 [INF] CMGR: Connecting to [2409:8a1a:168:b900:90c1:3a8a:caf9:c5e5]:16111
2021-12-15 00:45:38.806 [INF] CMGR: Connecting to 192.169.109.20:16111
2021-12-15 00:45:39.822 [INF] CMGR: Connecting to [2604:3d08:3387:b100::f34d]:16111
2021-12-15 00:45:40.832 [INF] CMGR: Connecting to [240e:474:2b40:dc2d:c406:8390:690d:1d]:16111
2021-12-15 00:45:41.840 [INF] CMGR: No ongoing connections, trying to get new addresses from seed...
2021-12-15 00:45:41.962 [INF] CMGR: DNS discovery failed on seed n.kaspa.turkel.in: lookup n.kaspa.turkel.in: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2021-12-15 00:45:42.158 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed.daglabs-dev.com
2021-12-15 00:45:42.158 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-2.kaspanet.org
2021-12-15 00:45:42.158 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-1.kaspanet.org
2021-12-15 00:46:03.750 [INF] CMGR: Connecting to 192.169.103.46:16111
2021-12-15 00:46:04.755 [INF] CMGR: Connecting to [2001:0:1428:8f18:2cbc:75f8:c189:a853]:16111
2021-12-15 00:46:05.766 [INF] CMGR: Connecting to 109.235.65.70:16111
2021-12-15 00:46:06.779 [INF] CMGR: Connecting to 65.108.46.189:16111
2021-12-15 00:46:07.781 [INF] CMGR: Connecting to [2408:8214:6311:4b91:c844:a3ed:70c5:6e3]:16111
2021-12-15 00:46:08.797 [INF] CMGR: Connecting to [2a00:23c8:9705:de00:514b:950d:39a3:cf93]:16111
2021-12-15 00:46:09.802 [INF] CMGR: Connecting to [2003:c1:2729:3ca3:e42a:c351:bb16:5d87]:16111
2021-12-15 00:46:10.819 [INF] CMGR: Connecting to [240e:330:3e96:9500:d8c8:14aa:6984:b90f]:16111
2021-12-15 00:46:11.823 [INF] CMGR: No ongoing connections, trying to get new addresses from seed...
2021-12-15 00:46:11.844 [INF] CMGR: DNS discovery failed on seed n.kaspa.turkel.in: lookup n.kaspa.turkel.in: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2021-12-15 00:46:11.900 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-1.kaspanet.org
2021-12-15 00:46:11.914 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed.daglabs-dev.com
2021-12-15 00:46:11.967 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-2.kaspanet.org
2021-12-15 00:46:33.753 [INF] CMGR: Connecting to 22.32.66.2:16111
2021-12-15 00:46:34.766 [INF] CMGR: Connecting to [240e:3b5:34e0:f191:34e5:8d4a:48f7:a73]:16111
2021-12-15 00:46:35.778 [INF] CMGR: Connecting to [2001:448a:5040:1c4d:39e5:7863:e784:1f69]:16111
2021-12-15 00:46:36.789 [INF] CMGR: Connecting to 192.169.1.253:16111
2021-12-15 00:46:37.804 [INF] CMGR: Connecting to [2a00:a040:19b:4731:10d2:1cce:ba95:691c]:16111
2021-12-15 00:46:38.811 [INF] CMGR: Connecting to 192.169.104.86:16111
2021-12-15 00:46:39.819 [INF] CMGR: Connecting to [2001:0:348b:fb58:20f3:e6c1:2db6:c20d]:16111
2021-12-15 00:46:40.827 [INF] CMGR: Connecting to [240e:474:ff5e:5e05:2833:3411:dbd:2e]:16111
2021-12-15 00:46:41.836 [INF] CMGR: No ongoing connections, trying to get new addresses from seed...
2021-12-15 00:46:41.874 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-1.kaspanet.org
2021-12-15 00:46:41.930 [INF] CMGR: DNS discovery failed on seed n.kaspa.turkel.in: lookup n.kaspa.turkel.in: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2021-12-15 00:46:41.939 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-2.kaspanet.org
2021-12-15 00:46:41.992 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed.daglabs-dev.com
2021-12-15 00:47:03.755 [INF] CMGR: Connecting to 192.169.108.77:16111
2021-12-15 00:47:04.761 [INF] CMGR: Connecting to 192.169.105.2:16111
2021-12-15 00:47:05.770 [INF] CMGR: Connecting to 192.169.103.32:16111
2021-12-15 00:47:06.785 [INF] CMGR: Connecting to [2001:0:348b:fb58:ce3:5359:34c8:f5df]:16111
2021-12-15 00:47:07.787 [INF] CMGR: Connecting to [2a00:a040:199:e7d4:71db:b9b3:49dd:8fec]:16111
2021-12-15 00:47:08.800 [INF] CMGR: Connecting to [2001:14ba:425a:9100:7897:7edb:6290:e8bc]:16111
2021-12-15 00:47:09.808 [INF] CMGR: Connecting to 192.169.103.54:16111
2021-12-15 00:47:10.822 [INF] CMGR: Connecting to [2a10:800a:bc65:0:4058:354c:2c08:364e]:16111
2021-12-15 00:47:11.825 [INF] CMGR: No ongoing connections, trying to get new addresses from seed...
2021-12-15 00:47:11.860 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-1.kaspanet.org
2021-12-15 00:47:11.911 [INF] CMGR: DNS discovery failed on seed n.kaspa.turkel.in: lookup n.kaspa.turkel.in: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2021-12-15 00:47:11.922 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-2.kaspanet.org
2021-12-15 00:47:11.922 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed.daglabs-dev.com
2021-12-15 00:47:33.759 [INF] CMGR: Connecting to [2a00:a040:19f:f4dd:51e6:9bd8:55e:47d7]:16111
2021-12-15 00:47:34.761 [INF] CMGR: Connecting to [240e:479:2408:fc4:d9fb:c61d:a7db:970a]:16111
2021-12-15 00:47:35.764 [INF] CMGR: Connecting to [2600:1700:d78:1cf0::46]:16111
2021-12-15 00:47:36.774 [INF] CMGR: Connecting to 192.169.109.114:16111
2021-12-15 00:47:37.774 [INF] CMGR: Connecting to [2001::1f0d:5604]:16111
2021-12-15 00:47:38.787 [INF] CMGR: Connecting to [2a00:fd40:1:655:303c:92d0:139b:247f]:16111
2021-12-15 00:47:39.789 [INF] CMGR: Connecting to [2001:41d0:2:9620::1]:16111
2021-12-15 00:47:40.792 [INF] CMGR: Connecting to [2408:8234:1812:311:5574:bb23:2977:d2db]:16111
2021-12-15 00:47:41.807 [INF] CMGR: No ongoing connections, trying to get new addresses from seed...
2021-12-15 00:47:41.878 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-1.kaspanet.org
2021-12-15 00:47:41.908 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-2.kaspanet.org
2021-12-15 00:47:41.908 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed.daglabs-dev.com
2021-12-15 00:47:41.923 [INF] CMGR: DNS discovery failed on seed n.kaspa.turkel.in: lookup n.kaspa.turkel.in: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2021-12-15 00:48:03.750 [INF] CMGR: Connecting to 192.169.107.1:16111
2021-12-15 00:48:04.762 [INF] CMGR: Connecting to [64:ff9b::23b1:7289]:16111
2021-12-15 00:48:05.764 [INF] CMGR: Connecting to [2409:8a20:24d2:d380:5518:767:294f:f1fc]:16111
2021-12-15 00:48:06.770 [INF] CMGR: Connecting to 18.130.119.167:16111
2021-12-15 00:48:07.773 [INF] CMGR: Connecting to 192.169.103.34:16111
2021-12-15 00:48:08.775 [INF] CMGR: Connecting to 192.169.108.120:16111
2021-12-15 00:48:09.789 [INF] CMGR: Connecting to 192.169.105.75:16111
2021-12-15 00:48:10.794 [INF] CMGR: Connecting to [2408:8214:6311:4b91:7535:4103:bd83:eadb]:16111
2021-12-15 00:48:11.807 [INF] CMGR: No ongoing connections, trying to get new addresses from seed...
2021-12-15 00:48:11.819 [INF] CMGR: DNS discovery failed on seed n.kaspa.turkel.in: lookup n.kaspa.turkel.in: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2021-12-15 00:48:11.840 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-1.kaspanet.org
2021-12-15 00:48:11.909 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed.daglabs-dev.com
2021-12-15 00:48:11.948 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-2.kaspanet.org
2021-12-15 00:48:33.749 [INF] CMGR: Connecting to [2a02:6680:2133:c08a:a9ba:f819:8a9a:5350]:16111
2021-12-15 00:48:34.758 [INF] CMGR: Connecting to 192.169.108.109:16111
2021-12-15 00:48:35.768 [INF] CMGR: Connecting to 192.169.101.65:16111
2021-12-15 00:48:36.780 [INF] CMGR: Connecting to [2002:49e5:5e81:0:7053:2aa8:a1ae:bba]:16111
2021-12-15 00:48:37.784 [INF] CMGR: Connecting to [2a0d:6fc0:1984:6900:c139:8b07:2c3c:b795]:16111
2021-12-15 00:48:38.793 [INF] CMGR: Connecting to [240e:458:604:769:7dbc:b840:8447:48f8]:16111
2021-12-15 00:48:39.805 [INF] CMGR: Connecting to [240e:3a1:86e:f620:9917:97:b2a9:4d1e]:16111
2021-12-15 00:48:40.809 [INF] CMGR: Connecting to [2409:8a45:71:f460:9dfb:f110:d78f:fdf2]:16111
2021-12-15 00:48:41.814 [INF] CMGR: No ongoing connections, trying to get new addresses from seed...
2021-12-15 00:48:41.826 [INF] CMGR: DNS discovery failed on seed n.kaspa.turkel.in: lookup n.kaspa.turkel.in: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2021-12-15 00:48:41.884 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-1.kaspanet.org
2021-12-15 00:48:41.910 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-2.kaspanet.org
2021-12-15 00:48:41.911 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed.daglabs-dev.com
2021-12-15 00:49:03.749 [INF] CMGR: Connecting to [2a00:a040:19a:1d2:7c03:e94d:e612:65e1]:16111
2021-12-15 00:49:04.764 [INF] CMGR: Connecting to 192.169.103.22:16111
2021-12-15 00:49:05.766 [INF] CMGR: Connecting to [240e:330:3e47:e100:4c78:8df4:1e2b:3015]:16111
2021-12-15 00:49:06.771 [INF] CMGR: Connecting to [2a02:1205:34e5:d230:c022:1fa6:7fae:2d8f]:16111
2021-12-15 00:49:07.786 [INF] CMGR: Connecting to [240e:361:375:1900:a532:6312:8241:c07c]:16111
2021-12-15 00:49:08.791 [INF] CMGR: Connecting to [2003:c1:2718:2add:d94f:efe5:e4f8:d175]:16111
2021-12-15 00:49:09.801 [INF] CMGR: Connecting to [240e:379:4dc7:a600:ec60:6b2b:c81c:e29e]:16111
2021-12-15 00:49:10.814 [INF] CMGR: Connecting to [240e:37b:a94:0:f418:f929:1651:ec21]:16111
2021-12-15 00:49:11.830 [INF] CMGR: No ongoing connections, trying to get new addresses from seed...
2021-12-15 00:49:11.845 [INF] CMGR: DNS discovery failed on seed n.kaspa.turkel.in: lookup n.kaspa.turkel.in: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2021-12-15 00:49:11.867 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-1.kaspanet.org
2021-12-15 00:49:11.930 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-2.kaspanet.org
2021-12-15 00:49:11.931 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed.daglabs-dev.com
2021-12-15 00:49:33.750 [INF] CMGR: Connecting to [240e:474:2b40:dc2d:a15f:65d9:42e3:c599]:16111
2021-12-15 00:49:34.760 [INF] CMGR: Connecting to [2408:820c:c31f:8c0:8b4:df1e:68e3:ad63]:16111
2021-12-15 00:49:35.765 [INF] CMGR: Connecting to [2a02:908:fbd2:26e0:c478:8169:7cae:533e]:16111
2021-12-15 00:49:36.773 [INF] CMGR: Connecting to [2a00:a040:199:d1fa:fe01:7cff:fe5b:c49]:16111
2021-12-15 00:49:37.780 [INF] CMGR: Connecting to [2409:893c:d20:2ef5:a80e:a23:6e51:2e18]:16111
2021-12-15 00:49:38.783 [INF] CMGR: Connecting to [240e:3b7:3277:ef70:68e1:a05:3ef6:85c5]:16111
2021-12-15 00:49:39.786 [INF] CMGR: Connecting to [2a01:e0a:847:d1d0:815a:1d00:2b9e:c3a2]:16111
2021-12-15 00:49:40.802 [INF] CMGR: Connecting to [64:ff9b::d28:43c0]:16111
2021-12-15 00:49:41.803 [INF] CMGR: No ongoing connections, trying to get new addresses from seed...
2021-12-15 00:49:41.827 [INF] CMGR: DNS discovery failed on seed n.kaspa.turkel.in: lookup n.kaspa.turkel.in: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2021-12-15 00:49:41.842 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-1.kaspanet.org
2021-12-15 00:49:41.891 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-2.kaspanet.org
2021-12-15 00:49:41.956 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed.daglabs-dev.com
2021-12-15 00:50:03.760 [INF] CMGR: Connecting to [2a00:a040:189:d2f9:4833:1c35:5a19:53fc]:16111
2021-12-15 00:50:04.772 [INF] CMGR: Connecting to [240e:398:ada1:3a40:54f5:3eb1:aeb6:c7ce]:16111
2021-12-15 00:50:05.774 [INF] CMGR: Connecting to [2a02:6680:2131:dff:e9a5:8f5a:55d:d734]:16111
2021-12-15 00:50:06.785 [INF] CMGR: Connecting to [64:ff9b::4d4e:63e5]:16111
2021-12-15 00:50:07.800 [INF] CMGR: Connecting to [2a00:a040:19a:1d2:84e:edc8:1c46:db22]:16111
2021-12-15 00:50:08.802 [INF] CMGR: Connecting to [2001:56a:75a5:da00:40b2:2a3f:728b:34eb]:16111
2021-12-15 00:50:09.803 [INF] CMGR: Connecting to [2409:8a0c:ee1c:2b50:25f8:9857:d4d7:9b48]:16111
2021-12-15 00:50:10.818 [INF] CMGR: Connecting to [2409:8a1a:168:b900:e01f:a8de:f96b:b671]:16111
2021-12-15 00:50:11.823 [INF] CMGR: No ongoing connections, trying to get new addresses from seed...
2021-12-15 00:50:11.842 [INF] CMGR: DNS discovery failed on seed n.kaspa.turkel.in: lookup n.kaspa.turkel.in: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2021-12-15 00:50:11.857 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-1.kaspanet.org
2021-12-15 00:50:11.914 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed-2.kaspanet.org
2021-12-15 00:50:11.919 [INF] CMGR: 16 addresses found from DNS seed n.mainnet-dnsseed.daglabs-dev.com
```

### LINKED ISSUE #1887: Kaspad crashes with "error in goroutine 'flow-HandleRelayInvs 297': not found\n key ... not found" message
While trying to sync from scratch kaspad crashed and reported the following:
2021-12-15 13:18:30.150 [CRT] PROT: Exiting: Fatal error in goroutine 'flow-HandleRelayInvs 297': not found
key 012f0f2f626c6f636b2d72656c6174696f6e732f98ce11799de94ab09e13767c221a6e02a2cbed9b64896fe5c659367ef927dda0 not found. 
Then this error kept appearing every next time kaspad is run. Here is the full DB+logs, archived after the 1st crash: https://transfer.sh/b5vSXj/kaspa-mainnet.rar

UPD: i now managed to successfully sync from scratch once I added custom peers 212.41.9.28, 168.119.79.146 and 65.108.46.86 - all the same from what I successfully synced the previous time. So this issue's source may be some node that's in a kind of 'unaligned' state

### PR DESCRIPTION
**Pull request by someone235**
1. `ArePruningPointsViolatingFinality` should check the recent pruning points first.
2. In `ValidatePruningPointProof` the pruning point parents at some level should be fetched from the header and not `dagTopologyManagers[blockLevel]` because the pruning point doesn't necessarily belong to that level.

Fixes #1886
Fixes #1887

### CODE REVIEW

**Review by michaelsutton — APPROVED** [review]

File: domain/consensus/processes/pruningmanager/pruningmanager.go [hunk 1]
```diff
@@ -513,8 +513,8 @@ func (pm *pruningManager) ArePruningPointsViolatingFinality(stagingArea *model.S
 		return false, err
 	}
 
-	for _, header := range pruningPoints {
-		blockHash := consensushashing.HeaderHash(header)
+	for i := len(pruningPoints) - 1; i >= 0; i-- {
```
Comment (michaelsutton) [inline domain/consensus/processes/pruningmanager/pruningmanager.go:516]: Perhaps add a comment explaining why the we must find the PP in future of virtual.F first (hence the reverse search)
